### PR TITLE
Fix BBCodes IMG URL

### PR DESCRIPTION
**Pull request by xBlackEye**
### Changes Proposed in this Pull Request:

@tyger07

### CODE REVIEW

**Comment by tyger07** [comment]
I am not able to reproduce the problem.  I wonder what conditions make it work or not work properly.
If I am understanding correctly, the problem you were having is that you were getting double forward slashes, but I only have a single forward slash without this fix.

**Comment by xBlackEye** [comment]
Check it here https://stats.bf4.emark.tk/index.php?sid=1&pid=1&p=player
OLD:
`[URL=https://stats.bf4.emark.tk/index.php?p=player&pid=1][IMG]https://stats.bf4.emark.tk//common/signature/signaturepid1fav0.png[/IMG][/URL]`
NEW:
`[URL=https://stats.bf4.emark.tk/index.php?p=player&pid=1][IMG]https://stats.bf4.emark.tk/common/signature/signaturepid1fav0.png[/IMG][/URL]`

**Comment by tyger07** [comment]
Oh, yes, I believe you.  My only concern is that I am not able to reproduce it in my test environment.

In my test environment, there is only one slash currently.  If I implement your change, in my test environment, there is then no slash in that portion of the URL, and then the URL doesn't work at all.  It seems that when a double slash happens, no harm is caused.  But when there is no slash, harm is caused.  So, it seems that the current implementation is better.

**Review by tyger07 — CHANGES_REQUESTED** [review]
Since not all server configurations do the double slashes (for some reason), find a different way to detect when double slashes occur, and remove the additional slash only when necessary.

**Comment by tyger07** [comment]
This has been fixed in a different method (which should work for both of us).  The fix should remove the additional slash when necessary, but not remove the slash when not necessary.
https://github.com/tyger07/BF4-Server-Stats/releases/tag/6-16-21

**Pull request closed without merging**
